# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                admin:
                  password: $2y$13$X87dpoYsBEFeNvzRtOugYOe5NJKvwYpecesCzamreNSb1YEhdvBdS
                  roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            pattern: ^/
            provider: in_memory
            form_login:
                username_parameter: _username
                default_target_path: offers
                login_path: login
                check_path: login
            logout: true
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }